# Generated by Django 5.1 on 2025-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.PositiveIntegerField(
                blank=True, max_length=20, null=True, verbose_name="Phone"
            ),
        ),
    ]
